-- Teaching assistant assignments and TA-managed office hours.
-- A TA remains a student in public.users; the assignment grants the extra capability.

CREATE OR REPLACE FUNCTION public.current_app_user_id()
RETURNS integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT id
  FROM public.users
  WHERE lower(email) = lower(COALESCE(auth.jwt() ->> 'email', ''))
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.current_app_user_role()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role::text
  FROM public.users
  WHERE id = public.current_app_user_id();
$$;

REVOKE ALL ON FUNCTION public.current_app_user_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.current_app_user_role() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.current_app_user_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_app_user_role() TO authenticated;

CREATE TABLE public.ta_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  faculty_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  assigned_by integer NOT NULL DEFAULT public.current_app_user_id()
    REFERENCES public.users(id) ON DELETE RESTRICT,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ta_assignments_different_users CHECK (student_id <> faculty_id)
);

CREATE INDEX ta_assignments_faculty_id_idx
  ON public.ta_assignments(faculty_id);
CREATE INDEX ta_assignments_active_idx
  ON public.ta_assignments(active);

CREATE TABLE public.ta_office_hours (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ta_assignment_id bigint NOT NULL
    REFERENCES public.ta_assignments(id) ON DELETE CASCADE,
  day text NOT NULL CHECK (day IN ('Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat')),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  location text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ta_office_hours_valid_range CHECK (end_time > start_time),
  CONSTRAINT ta_office_hours_unique_slot
    UNIQUE (ta_assignment_id, day, start_time, end_time)
);

CREATE INDEX ta_office_hours_assignment_day_idx
  ON public.ta_office_hours(ta_assignment_id, day, start_time);

CREATE OR REPLACE FUNCTION public.validate_ta_assignment()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.students WHERE user_id = NEW.student_id) THEN
    RAISE EXCEPTION 'TA must be an existing student';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.faculty WHERE user_id = NEW.faculty_id) THEN
    RAISE EXCEPTION 'TA must be assigned to an existing faculty member';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.users
    WHERE id = NEW.assigned_by AND role = 'admin'
  ) THEN
    RAISE EXCEPTION 'Only an admin can create or change a TA assignment';
  END IF;

  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER validate_ta_assignment_before_write
BEFORE INSERT OR UPDATE ON public.ta_assignments
FOR EACH ROW EXECUTE FUNCTION public.validate_ta_assignment();

ALTER TABLE public.ta_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ta_office_hours ENABLE ROW LEVEL SECURITY;

CREATE POLICY ta_assignments_select_authorized
ON public.ta_assignments
FOR SELECT
TO authenticated
USING (
  public.current_app_user_role() = 'admin'
  OR (
    active
    AND public.current_app_user_id() IN (student_id, faculty_id)
  )
);

CREATE POLICY ta_assignments_admin_insert
ON public.ta_assignments
FOR INSERT
TO authenticated
WITH CHECK (
  public.current_app_user_role() = 'admin'
  AND assigned_by = public.current_app_user_id()
);

CREATE POLICY ta_assignments_admin_update
ON public.ta_assignments
FOR UPDATE
TO authenticated
USING (public.current_app_user_role() = 'admin')
WITH CHECK (
  public.current_app_user_role() = 'admin'
  AND assigned_by = public.current_app_user_id()
);

CREATE POLICY ta_assignments_admin_delete
ON public.ta_assignments
FOR DELETE
TO authenticated
USING (public.current_app_user_role() = 'admin');

CREATE POLICY ta_office_hours_select_authorized
ON public.ta_office_hours
FOR SELECT
TO authenticated
USING (
  public.current_app_user_role() = 'admin'
  OR EXISTS (
    SELECT 1
    FROM public.ta_assignments assignment
    WHERE assignment.id = ta_assignment_id
      AND assignment.active
      AND public.current_app_user_id() IN (assignment.student_id, assignment.faculty_id)
  )
);

CREATE POLICY ta_office_hours_ta_insert
ON public.ta_office_hours
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.ta_assignments assignment
    WHERE assignment.id = ta_assignment_id
      AND assignment.active
      AND assignment.student_id = public.current_app_user_id()
  )
);

CREATE POLICY ta_office_hours_ta_update
ON public.ta_office_hours
FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.ta_assignments assignment
    WHERE assignment.id = ta_assignment_id
      AND assignment.active
      AND assignment.student_id = public.current_app_user_id()
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.ta_assignments assignment
    WHERE assignment.id = ta_assignment_id
      AND assignment.active
      AND assignment.student_id = public.current_app_user_id()
  )
);

CREATE POLICY ta_office_hours_ta_delete
ON public.ta_office_hours
FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.ta_assignments assignment
    WHERE assignment.id = ta_assignment_id
      AND assignment.active
      AND assignment.student_id = public.current_app_user_id()
  )
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.ta_assignments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ta_office_hours TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.ta_assignments_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.ta_office_hours_id_seq TO authenticated;
